### ISSUE TITLE
Incorrect generation within the Vinnytsia Council case

### ISSUE THREAD

**Issue by yukal** [tooleks/shevchenko-js#214] opened 2024-03-09 13:15 UTC
Expect:
```
1. Називний:	Вінницька Міська Рада
2. Родовий:	Вінницької Міської Ради
3. Давальний:	Вінницькій Міській Раді
4. Знахідний:	Вінницьку Міську Раду
5. Орудний:	Вінницькою Міською Радою
6. Місцевий:	у Вінницькій Міській Раді
7. Кличний:	О Вінницька Міська Радо!
```

Got:
```
1. Називний:  	Вінницька Міська Рада
2. Родовий:   	Вінницької Міськи Рада
3. Давальний: 	Вінницькій Місьці Рада
4. Знахідний: 	Вінницьку Міську Рада
5. Орудний:   	Вінницькою Міською Рада
6. Місцевий:  	Вінницькій Місьці Рада
7. Кличний:	Вінницька Місько Рада
```

**Comment by tooleks** [comment] 2024-03-10 12:01
The library is designed for the declension of the proper names of human beings.

Closing as the issue is out of the scope of the solution.

**Closed by tooleks** 2024-03-10 12:01 UTC
